"""Merge per-spacecraft submission fragments into one file, renumbering SC_ID and Line; validate; report J.
Usage: combine_submission.py out.txt frag1.txt frag2.txt ..."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from ctoc14.validator import validate, parse
out = sys.argv[1]; frags = sys.argv[2:]
line = 1
with open(out, 'w', encoding='utf-8') as f:
    f.write('# CTOC14 Problem A submission (generated by ctoc14 solver)\n')
    for sc, frag in enumerate(frags, 1):
        for row in parse(frag):
            f.write(f'{line} {sc} {row.event} {row.t:.17g} {row.r[0]:.17g} {row.r[1]:.17g} {row.r[2]:.17g} {row.v[0]:.17g} {row.v[1]:.17g} {row.v[2]:.17g} '
                    f'{row.m:.17g} {row.T[0]:.17g} {row.T[1]:.17g} {row.T[2]:.17g} {row.ast}\n')
            line += 1
print(f'wrote {out} with {line-1} rows from {len(frags)} spacecraft')
rep = validate(out)
